# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2
jobs:
  build:
    docker:
    machine:
      image: circleci/classic:edge

    working_directory: ~/rest-web

    steps:
      - checkout

      # - setup_remote_docker

      - run:
          name: image build
          command: |
            docker-compose up -d
            
      - run:
          name: docker-compose ps
          command: |
            docker-compose ps

      - run:
          name: test
          command: |
            docker-compose exec web bundle exec  rspec ./spec/models/
            
      - run:
          name: docker tag
          command: |
            docker tag ${OWNER}/rest-web:latest ${OWNER}/rest-web:latest

      - run:
          name: docker login
          command: |
            docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
          
      - run:
          name: docker push
          command: |
            docker push ${OWNER}/rest-web

workflows:
      version: 2
      build-master:
        jobs:
          - build:
              filters:
                branches:
                  only: master

